/**
 * V3 Elementor tree types — shared across all builder modules.
 *
 * The Elementor V3 `_elementor_data` JSON shape:
 *   [{ elType, widgetType?, settings, elements?, id }]
 *
 * Top-level entries are sections/containers (elType 'container' or 'section').
 * Widgets have elType 'widget' + widgetType ('heading','button','image',...).
 * Children live in `elements` (recursive).
 */

export type ElType = 'container' | 'section' | 'column' | 'widget';

export type WidgetType =
  | 'heading'
  | 'text-editor'
  | 'button'
  | 'image'
  | 'icon-box'
  | 'accordion'
  | 'html'
  | 'icon'
  | 'divider'
  | 'spacer'
  | 'video'
  | 'google_maps'
  | 'counter'
  | 'image-box'
  | 'gallery'
  | 'tabs';

/** A settings map value: primitives, nested objects (typography, background), arrays (tabs). */
export type SettingValue = unknown;

/** Settings are intentionally open-ended because Elementor settings are versioned by widget. */
export type SettingsMap = Record<string, unknown>;

export interface V3Element {
  /** Element type: 'container' | 'section' | 'column' | 'widget'. */
  elType: ElType;
  /** For widgets only. Elementor may add widget types across plugin versions. */
  widgetType?: string;
  /** Elementor settings map. */
  settings?: SettingsMap;
  /** Child elements (recursive). */
  elements?: V3Element[];
  /** Unique element id (generated by Elementor, e.g. 'a1b2c3d'). */
  id: string;
  /** Optional: original source label (for debugging — not part of Elementor data). */
  _source?: string;
  /** Optional: flag set by converters to indicate this element was auto-mapped. */
  _auto?: boolean;
}

/** A complete V3 page tree = array of top-level containers/sections. */
export type V3Tree = V3Element[];

/** Walk a V3 tree depth-first, yielding every element (including nested). */
export function* walkV3(tree: V3Tree): Generator<V3Element> {
  for (const el of tree) yield* walkEl(el);
}

function* walkEl(el: V3Element): Generator<V3Element> {
  yield el;
  if (el.elements) for (const c of el.elements) yield* walkEl(c);
}

/** Find all widgets of a given type in the tree. */
export function findWidgets(tree: V3Tree, type: WidgetType): V3Element[] {
  const out: V3Element[] = [];
  for (const el of walkV3(tree)) {
    if (el.elType === 'widget' && el.widgetType === type) out.push(el);
  }
  return out;
}

/** Find all containers that carry a given css_classes string. */
export function findContainersByClass(tree: V3Tree, className: string): V3Element[] {
  const out: V3Element[] = [];
  for (const el of walkV3(tree)) {
    if (el.elType !== 'container' && el.elType !== 'section') continue;
    const cls = el.settings?.css_classes;
    if (typeof cls === 'string' && cls.split(/\s+/).includes(className)) out.push(el);
  }
  return out;
}

/** Collect every external image URL referenced anywhere in the tree. */
export function collectImageUrls(tree: V3Tree): string[] {
  const urls = new Set<string>();
  for (const el of walkV3(tree)) {
    const s = el.settings ?? {};
    // image widget
    const img = s.image as { url?: string } | undefined;
    if (img?.url && typeof img.url === 'string') urls.add(img.url);
    // background_image
    const bg = s.background_image as { url?: string } | undefined;
    if (bg?.url && typeof bg.url === 'string') urls.add(bg.url);
    // html widget may contain <img src>
    if (el.widgetType === 'html' && typeof s.html === 'string') {
      for (const m of s.html.matchAll(/<img[^>]+src=["']([^"']+)["']/gi)) urls.add(m[1]);
    }
  }
  return [...urls];
}

/** Replace an image URL everywhere it appears in the tree (image widget + background_image). */
export function replaceImageUrl(tree: V3Tree, oldUrl: string, newUrl: string, attachmentId?: number): void {
  for (const el of walkV3(tree)) {
    const s = el.settings ?? {};
    const img = s.image as { url?: string; id?: number | null } | undefined;
    if (img?.url === oldUrl) {
      img.url = newUrl;
      if (attachmentId != null) img.id = attachmentId;
    }
    const bg = s.background_image as { url?: string; id?: number | null } | undefined;
    if (bg?.url === oldUrl) {
      bg.url = newUrl;
      if (attachmentId != null) bg.id = attachmentId;
    }
  }
}
