/**
 * ability-schema.ts — versioned ability-schema codegen (O-12 follow-up).
 *
 * Derives a consolidated, versioned JSON-Schema document for the Novamira
 * ability registry from the single source of truth — `KNOWN_ABILITIES` /
 * `ALIAS_MAP` / `UNAVAILABLE_ABILITIES` in `ability-registry.ts` (the frozen
 * snapshot of the live server, discovered 2026-07-30 against
 * testseite.nick-webdesign.de, see `docs/NOVAMIRA-LIVE-ABILITIES-2026-07-30.txt`).
 *
 * Analogue to the wizard-contract schema (O-12): the registry is the canonical
 * runtime artifact, and `abilityJsonSchemaDocument()` derives the deterministic
 * machine-readable document from it. The committed
 * `schemas/novamira-abilities.schema.json` is generated by
 * `scripts/export-ability-schema.ts`; a drift-guard test pins the committed
 * file to the generated document, so the schema can never silently fall out of
 * sync with the registry. A second guard test pins the registry back to the
 * live-abilities .txt capture.
 *
 * The document describes a "registry snapshot": the known ability names as an
 * enum, plus the alias map and the documented unavailable gaps, all carrying
 * the versioned `$id` (`elconv/novamira-abilities/v1`) and a `schemaVersion: 1`
 * machine gate shared with the wizard-contract family.
 */

import {
  KNOWN_ABILITIES,
  ALIAS_MAP,
  UNAVAILABLE_ABILITIES,
} from './ability-registry.js';

/** Stable identifier of the schema document a conforming registry snapshot refers to. */
export const ABILITY_SCHEMA_ID = 'elconv/novamira-abilities/v1';

/** Human-readable schema version, matching the `$id` suffix. */
export const ABILITY_SCHEMA_VERSION = 'v1';

/** Group an ability name into its namespace ('' for unnamespaced names). */
export function abilityNamespace(name: string): string {
  const idx = name.indexOf('/');
  return idx === -1 ? '' : name.slice(0, idx);
}

/**
 * Namespace → count of known abilities in that namespace, sorted by name for
 * determinism. A registry snapshot carries this so tooling can sanity-check
 * coverage without re-parsing the enum.
 */
export function abilityNamespaceCounts(known: readonly string[] = KNOWN_ABILITIES): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const name of known) {
    const ns = abilityNamespace(name);
    counts[ns] = (counts[ns] ?? 0) + 1;
  }
  return Object.fromEntries(Object.keys(counts).sort().map((ns) => [ns, counts[ns]]));
}

/**
 * Deterministic JSON-Schema document (draft 2020-12) derived from the ability
 * registry. The root describes a registry-snapshot object: `schemaVersion` (the
 * machine gate), `$schema` (self-description), `knownAbilities` (enum of every
 * live ability), `aliases` and `unavailableAbilities` (documented gaps), plus
 * `namespaceCounts` for coverage sanity-checks. `$defs.abilityName` is the
 * reusable enum so tools can reference a single ability without the wrapper.
 */
export function abilityJsonSchemaDocument(): Record<string, unknown> {
  const names = [...KNOWN_ABILITIES];
  return {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: ABILITY_SCHEMA_ID,
    title: 'Novamira ability registry snapshot',
    description:
      'Consolidated, versioned snapshot of the Novamira MCP ability registry: every known ability name (enum), the legacy-name alias map, documented unavailable gaps and per-namespace counts. Derived from KNOWN_ABILITIES in @elconv/mcp; see docs/NOVAMIRA-LIVE-ABILITIES-2026-07-30.txt.',
    version: ABILITY_SCHEMA_VERSION,
    type: 'object',
    properties: {
      schemaVersion: { const: 1 },
      $schema: { const: ABILITY_SCHEMA_ID },
      knownAbilities: {
        type: 'array',
        description: 'Every ability the live Novamira server exposes.',
        items: { $ref: '#/$defs/abilityName' },
        uniqueItems: true,
        minItems: 1,
      },
      aliases: {
        type: 'object',
        description: 'Legacy ability names mapped onto live ones (ALIAS_MAP).',
        additionalProperties: { $ref: '#/$defs/abilityName' },
      },
      unavailableAbilities: {
        type: 'object',
        description: 'Names referenced on purpose but not live (documented gaps).',
        additionalProperties: { type: 'string' },
      },
      namespaceCounts: {
        type: 'object',
        description: 'Per-namespace known-ability counts (deterministic, sorted).',
        additionalProperties: { type: 'integer', minimum: 0 },
      },
    },
    required: ['schemaVersion', '$schema', 'knownAbilities', 'aliases', 'unavailableAbilities'],
    $defs: {
      abilityName: {
        type: 'string',
        description: 'A live Novamira ability name (namespace/ability).',
        enum: names,
      },
    },
  };
}

/** Build the registry-snapshot payload that the schema describes. */
export function buildAbilityRegistrySnapshot(): {
  schemaVersion: 1;
  $schema: typeof ABILITY_SCHEMA_ID;
  knownAbilities: readonly string[];
  aliases: Readonly<Record<string, string>>;
  unavailableAbilities: Readonly<Record<string, string>>;
  namespaceCounts: Record<string, number>;
} {
  return {
    schemaVersion: 1,
    $schema: ABILITY_SCHEMA_ID,
    knownAbilities: KNOWN_ABILITIES,
    aliases: ALIAS_MAP,
    unavailableAbilities: UNAVAILABLE_ABILITIES,
    namespaceCounts: abilityNamespaceCounts(),
  };
}
